server:
  port: 8011
  
spring:
  application:
    name: config-server
  # config
  cloud:
    config:
      server:
        git:
          uri: git@gitee.com:mytt_10566/config-server.git
          search-paths: config-repo
          username:
          password: 
    
  