server:
  port: 8092
  
spring:
  application:
    name: config-server
  # config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:njittsscloud/config-server.git
          search-paths: config-repo
          username:
          password:

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
          
security:
  user:
    name: admin
    password: admin

# 对称性秘钥    
#encrypt: 
#  key: tss
    
  