server:
  port: 8092
  
spring:
  application:
    name: tss-config-server
  # config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:njittsscloud/config-server.git
          search-paths: config-repo
          username:
          password:

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
     
security:
  user:
    name: admin
    password: admin

# 对称性秘钥    
#encrypt: 
#  key: tss
    
  