server:
  port: 8011
  
spring:
  application:
    name: config-server
  # config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/mytt_10566/config-server
          search-paths:
          username:
          password: 
    
  