server:
  port: 8011
  
spring:
  application:
    name: config-server
  # config
  cloud:
    config:
      server:
        git:
          uri:
          search-paths:
          username:
          password: 
    
  